### ISSUE TITLE
Time tracking

### ISSUE THREAD

**Issue by mvuajua** [mvuajua/accountable#5]
- [ ] start / stop timer
- [ ] add time manually
- [ ] assign time to customer / project
